### ISSUE TITLE
Edge case. Failure of harverster when nothing to do

### ISSUE THREAD

**Issue by derfredy** [Colm3na/polkastats-backend-v3#2]
Sometimes after harverster docker start you see this log:

[PolkaStats backend v3] - Block harvester - Detected gap! Harvest blocks from #0 to #0
[PolkaStats backend v3] - Block harvester - Error adding block #0: error: duplicate key value violates unique constraint "block_pkey"
    at Connection.parseE (/usr/app/polkastats-backend-v3/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/usr/app/polkastats-backend-v3/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/usr/app/polkastats-backend-v3/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[PolkaStats backend v3] - Block harvester - Total execution time: 6s

It seems to happen when nothing to do. It finds a gap between block 0 and 0, what does not make sense.

**Comment by mariopino** [comment]
Thanks Fredy! I know this nasty error log, the good news is that it has no effect in the harvesting process.  This is caused by the SQL query to detect the gaps in the blocks table, in some cases, it returns the gap [ from #0 to #0]  which is wrong (and genesis block actually exist in the db!). So I have to debug it! ;-)

**Comment by mariopino** [comment]
Added a workaround for this in develop.
